export default {
  admin: [
    "monitor",
    "education",
    "employee",
    "calendar",
    "tasks",
    "reports",
    "clients",
    "orders",
    "mail",
    "goods",
    "seo",
    "mango",
    "storage",
    "delivery",
    "callbacks",
    "buying",
  ],
  buyer: [
    "monitor",
    "education",
    "calendar",
    "reports",
    "clients",
    "orders",
    "mail",
    "storage",
    "delivery",
  ],
  call: [
    "monitor",
    "education",
    "employee",
    "calendar",
    "orders",
    "mail",
    "mango",
    "delivery",
    "callbacks",
  ],
  content: ["monitor", "education", "calendar", "goods", "tasks", "sites"],
  director: [
    "monitor",
    "education",
    "employee",
    "calendar",
    "tasks",
    "reports",
    "clients",
    "orders",
    "mail",
    "goods",
    "seo",
    "mango",
    "storage",
    "delivery",
    "callbacks",
    "buying",
  ],
  manager: [
    "monitor",
    "education",
    "calendar",
    "tasks",
    "orders",
    "mail",
    "goods",
    "delivery",
    "callbacks",
    "buying",
  ],
  seo: ["monitor", "education", "calendar", "tasks", "reports", "seo", "sites"],
  superadmin: [
    "monitor",
    "education",
    "employee",
    "calendar",
    "tasks",
    "reports",
    "orders",
    "clients",
    "mail",
    "goods",
    "seo",
    "mango",
    "storage",
    "delivery",
    "callbacks",
    "buying",
    "sites",
  ],
};
