const path = require('path')

exports.TEMP_PATH = path.join(__dirname, '..', 'temp')
exports.AVATARS_PATH = path.join(__dirname, '..', 'static/avatars')
exports.PASSPORTS_PATH = path.join(__dirname, '..', 'static/passports')
exports.ROOT = path.join(__dirname, '..', '/')

exports.PRODUCTS_PATH = path.join(__dirname, '..', 'uploads/products')
exports.UPLOADS_PATH = path.join(__dirname, '..', 'uploads')
exports.SALES_PATH = path.join(__dirname, '..', 'uploads/sales')
exports.CATEGORIES_PATH = path.join(__dirname, '..', 'uploads/categories')
exports.BRANDS_PATH = path.join(__dirname, '..', 'uploads/brands')
exports.DOCUMENTS_PATH = path.join(__dirname, '..', 'uploads/documents/tasks')
exports.REGIONS_PATH = path.join(__dirname, '..', 'uploads/documents/regions')
exports.USERS_PATH = path.join(__dirname, '..', 'uploads/documents/users')
exports.CALLBACKS_PATH = path.join(__dirname, '..', 'uploads/callbacks/')
exports.EDUCATION_PATH = path.join(__dirname, '..', 'uploads/educations/')
exports.ORDERS_PATH = path.join(__dirname, '..', 'uploads/documents/orders')
exports.SEO_PATH = path.join(__dirname, '..', 'uploads/seo')
exports.ONEC_PATH = path.join(__dirname, '..', 'uploads/onec')
exports.FEEDS_PATH = path.join(__dirname, '..', 'uploads/feeds')
exports.G_DOCS_PRODUCTS_PATH = path.join(__dirname, '..', 'uploads/googledocs/products')
exports.STATIC_SITES_PATH = path.join(__dirname, '..', 'uploads/staticsites')